//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.sspu.bean;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class CapitalBean_
    extends CapitalBean
{

    private Context context_;
    private static CapitalBean_ instance_;

    private CapitalBean_(Context context) {
        context_ = context;
    }

    public static CapitalBean_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new CapitalBean_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
